version: "3.6"
services:
    anon:
        build: .
        volumes:
            - ${INPUT_FOLDER}:/input
            - ${OUTPUT_FOLDER}:/output
            - .//weights:/weights
        dns:
            8.8.4.4
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
